# Generated by Django 6.0.6 on 2026-06-05 13:07

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0001_initial'),
        ('schools', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='código')),
                ('name', models.CharField(max_length=200, verbose_name='nome')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('phone_number', models.CharField(blank=True, max_length=30, verbose_name='telefone')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo')], default='active', max_length=20, verbose_name='status')),
                ('max_weekly_load', models.PositiveIntegerField(blank=True, null=True, verbose_name='carga semanal máxima')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'professor',
                'verbose_name_plural': 'professores',
                'ordering': ['name', 'email'],
            },
        ),
        migrations.CreateModel(
            name='TeacherAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('weekday', models.CharField(choices=[('monday', 'Segunda-feira'), ('tuesday', 'Terça-feira'), ('wednesday', 'Quarta-feira'), ('thursday', 'Quinta-feira'), ('friday', 'Sexta-feira'), ('saturday', 'Sábado'), ('sunday', 'Domingo')], max_length=20, verbose_name='dia da semana')),
                ('start_time', models.TimeField(verbose_name='hora de início')),
                ('end_time', models.TimeField(verbose_name='hora de término')),
                ('is_available', models.BooleanField(default=True, verbose_name='disponível')),
                ('reason', models.TextField(blank=True, verbose_name='motivo')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='people.teacher', verbose_name='professor')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_availabilities', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'disponibilidade do professor',
                'verbose_name_plural': 'disponibilidades dos professores',
                'ordering': ['teacher__name', 'weekday', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='TeacherQualification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='válida desde')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='válida até')),
                ('status', models.CharField(choices=[('active', 'Ativa'), ('inactive', 'Inativa')], default='active', max_length=20, verbose_name='status')),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_qualifications', to='schools.series', verbose_name='série')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_qualifications', to='curriculum.subject', verbose_name='disciplina')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='people.teacher', verbose_name='professor')),
                ('teaching_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_qualifications', to='schools.teachinglevel', verbose_name='nível de ensino')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_qualifications', to='tenants.tenant', verbose_name='tenant')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_qualifications', to='schools.unit', verbose_name='unidade')),
            ],
            options={
                'verbose_name': 'habilitação do professor',
                'verbose_name_plural': 'habilitações dos professores',
                'ordering': ['teacher__name', 'id'],
            },
        ),
    ]
