# Generated by Django 6.0.6 on 2026-06-05 11:03

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumMatrix',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200, verbose_name='nome')),
                ('version', models.CharField(max_length=50, verbose_name='versão')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('active', 'Ativa'), ('inactive', 'Inativa')], default='draft', max_length=20, verbose_name='status')),
                ('effective_from', models.DateField(blank=True, null=True, verbose_name='vigente desde')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='vigente até')),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_matrices', to='schools.series', verbose_name='série')),
                ('teaching_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_matrices', to='schools.teachinglevel', verbose_name='nível de ensino')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_matrices', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'matriz curricular',
                'verbose_name_plural': 'matrizes curriculares',
                'ordering': ['name', 'version'],
            },
        ),
        migrations.CreateModel(
            name='InheritanceRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('source_type', models.CharField(choices=[('tenant', 'Tenant'), ('teaching_level', 'Nível de ensino'), ('series', 'Série'), ('unit', 'Unidade'), ('class_group', 'Turma'), ('curriculum_matrix', 'Matriz curricular'), ('workload_item', 'Item de carga horária'), ('subject', 'Disciplina')], max_length=50, verbose_name='tipo de origem')),
                ('source_id', models.UUIDField(verbose_name='origem')),
                ('target_type', models.CharField(choices=[('tenant', 'Tenant'), ('teaching_level', 'Nível de ensino'), ('series', 'Série'), ('unit', 'Unidade'), ('class_group', 'Turma'), ('curriculum_matrix', 'Matriz curricular'), ('workload_item', 'Item de carga horária'), ('subject', 'Disciplina')], max_length=50, verbose_name='tipo de destino')),
                ('target_id', models.UUIDField(verbose_name='destino')),
                ('rule_type', models.CharField(choices=[('weekly_load', 'Carga semanal'), ('subject', 'Disciplina'), ('double_lesson', 'Aula dupla'), ('share_allowed', 'Compartilhamento'), ('curriculum_scope', 'Escopo curricular')], max_length=50, verbose_name='tipo da regra')),
                ('priority', models.IntegerField(default=0, verbose_name='prioridade')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inheritance_rules', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'regra de herança',
                'verbose_name_plural': 'regras de herança',
                'ordering': ['-priority', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LocalException',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('scope_type', models.CharField(choices=[('teaching_level', 'Nível de ensino'), ('series', 'Série'), ('unit', 'Unidade'), ('class_group', 'Turma'), ('curriculum_matrix', 'Matriz curricular'), ('workload_item', 'Item de carga horária'), ('subject', 'Disciplina')], max_length=50, verbose_name='tipo de escopo')),
                ('scope_id', models.UUIDField(verbose_name='escopo')),
                ('original_value', models.JSONField(default=dict, verbose_name='valor original')),
                ('override_value', models.JSONField(default=dict, verbose_name='valor sobrescrito')),
                ('reason', models.TextField(verbose_name='motivo')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('inheritance_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_exceptions', to='curriculum.inheritancerule', verbose_name='regra de herança')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_exceptions', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'exceção local',
                'verbose_name_plural': 'exceções locais',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='código')),
                ('name', models.CharField(max_length=200, verbose_name='nome')),
                ('slug', models.SlugField(blank=True, verbose_name='slug')),
                ('status', models.CharField(choices=[('active', 'Ativa'), ('inactive', 'Inativa')], default='active', max_length=20, verbose_name='status')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'disciplina',
                'verbose_name_plural': 'disciplinas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubjectRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('rule_type', models.CharField(choices=[('weekly_load', 'Carga semanal'), ('double_lesson', 'Aula dupla'), ('share_allowed', 'Compartilhamento'), ('distribution', 'Distribuição semanal')], max_length=50, verbose_name='tipo da regra')),
                ('payload', models.JSONField(default=dict, verbose_name='payload')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_rules', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'regra de disciplina',
                'verbose_name_plural': 'regras de disciplina',
                'ordering': ['rule_type', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WorkloadItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('weekly_lessons', models.PositiveIntegerField(verbose_name='aulas semanais')),
                ('lesson_duration_min', models.PositiveIntegerField(verbose_name='duração da aula em minutos')),
                ('is_double_lesson', models.BooleanField(default=False, verbose_name='aula dupla')),
                ('can_share', models.BooleanField(default=False, verbose_name='pode compartilhar horário')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('class_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workload_items', to='schools.classgroup', verbose_name='turma')),
                ('curriculum_matrix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workload_items', to='curriculum.curriculummatrix', verbose_name='matriz curricular')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workload_items', to='schools.series', verbose_name='série')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workload_items', to='curriculum.subject', verbose_name='disciplina')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workload_items', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'item de carga horária',
                'verbose_name_plural': 'itens de carga horária',
                'ordering': ['curriculum_matrix__name', 'subject__name'],
            },
        ),
    ]
