# Generated by Django 6.0.6 on 2026-06-05 15:08

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0001_initial'),
        ('people', '0001_initial'),
        ('schools', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('weekday', models.CharField(choices=[('monday', 'Segunda-feira'), ('tuesday', 'Terça-feira'), ('wednesday', 'Quarta-feira'), ('thursday', 'Quinta-feira'), ('friday', 'Sexta-feira'), ('saturday', 'Sábado'), ('sunday', 'Domingo')], max_length=20, verbose_name='dia da semana')),
                ('start_time', models.TimeField(verbose_name='hora de início')),
                ('end_time', models.TimeField(verbose_name='hora de término')),
                ('order', models.PositiveIntegerField(verbose_name='ordem')),
                ('slot_type', models.CharField(choices=[('class', 'Aula'), ('interval', 'Intervalo'), ('lunch', 'Almoço'), ('blocked', 'Bloqueado')], default='class', max_length=20, verbose_name='tipo')),
                ('accepts_double_lesson', models.BooleanField(default=False, verbose_name='aceita dobradinha')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
            ],
            options={
                'verbose_name': 'slot',
                'verbose_name_plural': 'slots',
                'ordering': ['weekday', 'order', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='TimetableVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('version_number', models.PositiveIntegerField(verbose_name='número da versão')),
                ('name', models.CharField(max_length=200, verbose_name='nome')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('validated', 'Validada'), ('published', 'Publicada'), ('archived', 'Arquivada')], default='draft', max_length=20, verbose_name='status')),
                ('is_current', models.BooleanField(default=False, verbose_name='versão atual')),
            ],
            options={
                'verbose_name': 'versão de grade',
                'verbose_name_plural': 'versões de grade',
                'ordering': ['-version_number', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Validation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('scope_type', models.CharField(choices=[('timetable_version', 'Versão de grade'), ('timetable', 'Grade de horários'), ('lesson_assignment', 'Aula alocada')], max_length=30, verbose_name='tipo de escopo')),
                ('scope_id', models.UUIDField(verbose_name='escopo')),
                ('validation_type', models.CharField(choices=[('operational', 'Operacional')], max_length=30, verbose_name='tipo de validação')),
                ('status', models.CharField(choices=[('valid', 'Válida'), ('invalid', 'Inválida')], max_length=20, verbose_name='status')),
                ('message', models.CharField(max_length=255, verbose_name='mensagem')),
                ('details', models.JSONField(default=dict, verbose_name='detalhes')),
            ],
            options={
                'verbose_name': 'validação',
                'verbose_name_plural': 'validações',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Conflict',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('scope_type', models.CharField(choices=[('timetable_version', 'Versão de grade'), ('timetable_slot', 'Slot'), ('lesson_assignment', 'Aula alocada'), ('lesson_component', 'Componente de aula')], max_length=30, verbose_name='tipo de escopo')),
                ('scope_id', models.UUIDField(verbose_name='escopo')),
                ('code', models.CharField(choices=[('missing_assignment', 'Slot vazio'), ('teacher_overlap', 'Conflito de professor'), ('duplicate_class_slot', 'Turma duplicada no mesmo slot'), ('teacher_unavailable', 'Professor indisponível'), ('teacher_unqualified', 'Professor sem habilitação'), ('double_lesson_sequence', 'Dobradinha inválida')], max_length=50, verbose_name='código')),
                ('severity', models.CharField(choices=[('error', 'Erro'), ('warning', 'Aviso')], max_length=20, verbose_name='severidade')),
                ('message', models.CharField(max_length=255, verbose_name='mensagem')),
                ('details', models.JSONField(default=dict, verbose_name='detalhes')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='resolvido em')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'conflito',
                'verbose_name_plural': 'conflitos',
                'ordering': ['severity', 'code', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='LessonAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('planned', 'Planejada'), ('fixed', 'Fixa'), ('validated', 'Validada'), ('conflict', 'Com conflito')], default='planned', max_length=20, verbose_name='status')),
                ('allocation_source_type', models.CharField(choices=[('manual', 'Manual'), ('suggested', 'Sugerida'), ('generated', 'Gerada')], default='manual', max_length=20, verbose_name='origem da alocação')),
                ('allocation_source_id', models.UUIDField(blank=True, null=True, verbose_name='origem da alocação id')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_assignments', to='schools.classgroup', verbose_name='turma')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_assignments', to='curriculum.subject', verbose_name='disciplina')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_assignments', to='people.teacher', verbose_name='professor')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_assignments', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'aula alocada',
                'verbose_name_plural': 'aulas alocadas',
                'ordering': ['slot__weekday', 'slot__order', 'class_group__name'],
            },
        ),
        migrations.CreateModel(
            name='LessonComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('component_type', models.CharField(choices=[('main', 'Principal'), ('support', 'Apoio'), ('shared', 'Compartilhada'), ('subgroup', 'Subgrupo')], max_length=20, verbose_name='tipo do componente')),
                ('order', models.PositiveIntegerField(verbose_name='ordem')),
                ('duration_min', models.PositiveIntegerField(verbose_name='duração em minutos')),
                ('subgroup_label', models.CharField(blank=True, max_length=50, verbose_name='subgrupo')),
                ('lesson_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='scheduling.lessonassignment', verbose_name='aula alocada')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_components', to='curriculum.subject', verbose_name='disciplina')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_components', to='people.teacher', verbose_name='professor')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_components', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'componente de aula',
                'verbose_name_plural': 'componentes de aula',
                'ordering': ['lesson_assignment__slot__weekday', 'lesson_assignment__slot__order', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200, verbose_name='nome')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('active', 'Ativa'), ('archived', 'Arquivada')], default='draft', max_length=20, verbose_name='status')),
                ('current_version_number', models.PositiveIntegerField(default=1, verbose_name='versão atual')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='schools.period', verbose_name='período')),
            ],
            options={
                'verbose_name': 'grade de horários',
                'verbose_name_plural': 'grades de horários',
                'ordering': ['unit__name', 'period__order', 'name'],
            },
        ),
    ]
