# Generated by Django 6.0.6 on 2026-06-05 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduling', '0001_initial'),
        ('schools', '0002_schoolyear'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='school_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='schools.schoolyear', verbose_name='ano letivo'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='tenants.tenant', verbose_name='tenant'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='schools.unit', verbose_name='unidade'),
        ),
        migrations.AddField(
            model_name='timetableslot',
            name='timetable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='scheduling.timetable', verbose_name='grade de horários'),
        ),
        migrations.AddField(
            model_name='lessonassignment',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_assignments', to='scheduling.timetableslot', verbose_name='slot'),
        ),
        migrations.AddField(
            model_name='timetableversion',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_versions', to='tenants.tenant', verbose_name='tenant'),
        ),
        migrations.AddField(
            model_name='timetableversion',
            name='timetable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='scheduling.timetable', verbose_name='grade de horários'),
        ),
        migrations.AddField(
            model_name='lessonassignment',
            name='timetable_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_assignments', to='scheduling.timetableversion', verbose_name='versão de grade'),
        ),
        migrations.AddField(
            model_name='validation',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='tenants.tenant', verbose_name='tenant'),
        ),
        migrations.AddField(
            model_name='conflict',
            name='validation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='scheduling.validation', verbose_name='validação'),
        ),
        migrations.AddConstraint(
            model_name='timetableslot',
            constraint=models.UniqueConstraint(fields=('timetable', 'weekday', 'order'), name='unique_timetable_weekday_slot_order'),
        ),
        migrations.AddConstraint(
            model_name='timetableversion',
            constraint=models.UniqueConstraint(fields=('timetable', 'version_number'), name='unique_timetable_version_number'),
        ),
    ]
