# Generated by Django 6.0.6 on 2026-06-14 01:50

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_initial'),
        ('schools', '0004_schoolyear_last_solver_run_at'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolverVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('nome', models.CharField(choices=[('A-Restart', 'A - Restart'), ('B-HillClimbing', 'B - Hill Climbing'), ('C-Hybrid', 'C - Híbrido')], max_length=30, verbose_name='nome')),
                ('descricao', models.TextField(blank=True, default='', verbose_name='descrição')),
                ('is_active', models.BooleanField(default=True, help_text='Variantes inativas não são executadas pelo pipeline.', verbose_name='ativa')),
                ('parametros', models.JSONField(blank=True, default=dict, help_text='Parâmetros da variante: seed, timeout, max_restarts, max_construcoes, etc.', verbose_name='parâmetros')),
                ('school_year', models.ForeignKey(blank=True, help_text='Se vazio, a variante é global (todos os anos letivos do tenant).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solver_variants', to='schools.schoolyear', verbose_name='ano letivo')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solver_variants', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'variante do solver',
                'verbose_name_plural': 'variantes do solver',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='SolverRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='início')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='término')),
                ('status', models.CharField(choices=[('running', 'Rodando'), ('success', 'Sucesso'), ('failed', 'Falhou'), ('interrupted', 'Interrompida')], default='running', max_length=20, verbose_name='status')),
                ('buracos', models.PositiveIntegerField(blank=True, null=True, verbose_name='buracos')),
                ('completude', models.FloatField(blank=True, help_text='Fração 0.0–1.0 de aulas alocadas.', null=True, verbose_name='completude')),
                ('tempo_ate_1a_solucao', models.DurationField(blank=True, null=True, verbose_name='tempo até 1ª solução')),
                ('tempo_total', models.DurationField(blank=True, null=True, verbose_name='tempo total')),
                ('iteracoes', models.PositiveIntegerField(default=0, verbose_name='iterações')),
                ('restarts', models.PositiveIntegerField(default=0, verbose_name='restarts')),
                ('criterio_parada', models.CharField(blank=True, choices=[('timeout', 'Timeout'), ('zero_buracos', 'Zero buracos'), ('erro', 'Erro'), ('interrupted', 'Interrompido')], max_length=20, null=True, verbose_name='critério de parada')),
                ('seed', models.PositiveIntegerField(default=0, verbose_name='seed')),
                ('solution_json', models.JSONField(blank=True, help_text='Solution serializada via to_dict(). Pode ser grande.', null=True, verbose_name='solução')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='mensagem de erro')),
                ('disparado_por', models.CharField(choices=[('user', 'Usuário'), ('cron', 'Cron'), ('api', 'API')], default='user', max_length=10, verbose_name='disparado por')),
                ('suggestions_status', models.CharField(choices=[('not_run', 'Não executada'), ('running', 'Rodando'), ('done', 'Concluída'), ('timeout', 'Timeout'), ('disabled', 'Desativada'), ('failed', 'Falhou')], default='not_run', max_length=15, verbose_name='status das sugestões')),
                ('suggestions_count', models.PositiveIntegerField(default=0, verbose_name='nº de sugestões')),
                ('report_upload_status', models.CharField(choices=[('pending', 'Pendente'), ('success', 'Sucesso'), ('failed', 'Falhou'), ('disabled', 'Desativada')], default='pending', max_length=10, verbose_name='status do upload do relatório')),
                ('disparado_por_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solver_runs', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solver_runs', to='schools.schoolyear', verbose_name='ano letivo')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solver_runs', to='tenants.tenant', verbose_name='tenant')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='scheduling.solvervariant', verbose_name='variante')),
            ],
            options={
                'verbose_name': 'execução do solver',
                'verbose_name_plural': 'execuções do solver',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='solvervariant',
            constraint=models.UniqueConstraint(fields=('tenant', 'school_year', 'nome'), name='unique_solver_variant_per_scope'),
        ),
        migrations.AddIndex(
            model_name='solverrun',
            index=models.Index(fields=['school_year', '-created_at'], name='scheduling__school__582d8b_idx'),
        ),
        migrations.AddIndex(
            model_name='solverrun',
            index=models.Index(fields=['variant', '-created_at'], name='scheduling__variant_c8a582_idx'),
        ),
        migrations.AddIndex(
            model_name='solverrun',
            index=models.Index(fields=['tenant', '-created_at'], name='scheduling__tenant__74ba5a_idx'),
        ),
    ]
