# Generated by Django 6.0.6 on 2026-06-17 05:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_seed_default_variants'),
        ('schools', '0005_schoolyear_suggestions_enabled'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('categoria', models.CharField(choices=[('workload_increase', 'Aumentar carga horária'), ('teacher_add', 'Adicionar professor'), ('teacher_availability', 'Expandir disponibilidade'), ('subject_rule_relax', 'Relaxar regra')], max_length=30, verbose_name='categoria')),
                ('titulo', models.CharField(max_length=200, verbose_name='título')),
                ('descricao', models.TextField(blank=True, default='', verbose_name='descrição')),
                ('buracos_antes', models.PositiveIntegerField(default=0, verbose_name='buracos antes')),
                ('buracos_depois', models.PositiveIntegerField(default=0, verbose_name='buracos depois')),
                ('delta', models.IntegerField(default=0, help_text='Redução no nº de buracos (buracos_antes - buracos_depois).', verbose_name='delta')),
                ('param_diff', models.JSONField(blank=True, default=dict, verbose_name='parâmetros alterados')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('applied', 'Aplicada'), ('ignored', 'Ignorada')], default='pending', max_length=10, verbose_name='status')),
                ('aplicado_em', models.DateTimeField(blank=True, null=True, verbose_name='aplicada em')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='schools.schoolyear', verbose_name='ano letivo')),
                ('solver_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='scheduling.solverrun', verbose_name='execução do solver')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'sugestão',
                'verbose_name_plural': 'sugestões',
                'ordering': ['-delta'],
                'indexes': [models.Index(fields=['school_year', '-created_at'], name='suggestion_school_year_created'), models.Index(fields=['solver_run'], name='suggestion_solver_run')],
            },
        ),
    ]
