# Generated by Django 6.0.6 on 2026-06-05 09:05

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachingLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='código')),
                ('name', models.CharField(max_length=200, verbose_name='nome')),
                ('order', models.PositiveIntegerField(verbose_name='ordem')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo')], default='active', max_length=20, verbose_name='status')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_levels', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'nível de ensino',
                'verbose_name_plural': 'níveis de ensino',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='código')),
                ('name', models.CharField(max_length=200, verbose_name='nome')),
                ('order', models.PositiveIntegerField(verbose_name='ordem')),
                ('status', models.CharField(choices=[('active', 'Ativa'), ('inactive', 'Inativa')], default='active', max_length=20, verbose_name='status')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_set', to='tenants.tenant', verbose_name='tenant')),
                ('teaching_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='schools.teachinglevel', verbose_name='nível de ensino')),
            ],
            options={
                'verbose_name': 'série',
                'verbose_name_plural': 'séries',
                'ordering': ['teaching_level__order', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='código')),
                ('name', models.CharField(max_length=200, verbose_name='nome')),
                ('status', models.CharField(choices=[('active', 'Ativa'), ('inactive', 'Inativa')], default='active', max_length=20, verbose_name='status')),
                ('timezone', models.CharField(blank=True, max_length=64, verbose_name='fuso horário')),
                ('default_settings', models.JSONField(blank=True, default=dict, verbose_name='configurações padrão')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'unidade',
                'verbose_name_plural': 'unidades',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200, verbose_name='nome')),
                ('type', models.CharField(choices=[('morning', 'Manhã'), ('afternoon', 'Tarde'), ('evening', 'Noite')], max_length=20, verbose_name='tipo')),
                ('order', models.PositiveIntegerField(verbose_name='ordem')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo')], default='active', max_length=20, verbose_name='status')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='hora de início')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='hora de término')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='tenants.tenant', verbose_name='tenant')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='schools.unit', verbose_name='unidade')),
            ],
            options={
                'verbose_name': 'período',
                'verbose_name_plural': 'períodos',
                'ordering': ['unit__name', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ClassGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='código')),
                ('name', models.CharField(max_length=200, verbose_name='nome')),
                ('status', models.CharField(choices=[('active', 'Ativa'), ('inactive', 'Inativa')], default='active', max_length=20, verbose_name='status')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_groups', to='tenants.tenant', verbose_name='tenant')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_groups', to='schools.period', verbose_name='período')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_groups', to='schools.series', verbose_name='série')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_groups', to='schools.unit', verbose_name='unidade')),
            ],
            options={
                'verbose_name': 'turma',
                'verbose_name_plural': 'turmas',
                'ordering': ['name'],
            },
        ),
    ]
