# Generated by Django 6.0.6 on 2026-06-05 15:08

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolYear',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200, verbose_name='nome')),
                ('year', models.PositiveIntegerField(verbose_name='ano')),
                ('start_date', models.DateField(verbose_name='data de início')),
                ('end_date', models.DateField(verbose_name='data de término')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('active', 'Ativo'), ('archived', 'Arquivado')], default='draft', max_length=20, verbose_name='status')),
                ('is_active', models.BooleanField(default=False, verbose_name='ativo')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_years', to='tenants.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'ano letivo',
                'verbose_name_plural': 'anos letivos',
                'ordering': ['-year', 'name'],
            },
        ),
    ]
