# Generated by Django 6.0.6 on 2026-06-14 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_sprint07_unit_period_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolyear',
            name='last_solver_run_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Cooldown: 1 execução por hora (desativado em local/dev/test). Ver SDD §22.2.4.', null=True, verbose_name='última execução do solver'),
        ),
    ]
