# Generated by Django 6.0.6 on 2026-06-17 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_schoolyear_last_solver_run_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolyear',
            name='suggestions_enabled',
            field=models.BooleanField(default=True, help_text='Se Falso, a camada de sugestões não roda para este ano letivo.', verbose_name='sugestões ativadas'),
        ),
    ]
